# Generated by Django 2.0 on 2018-08-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_workout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
