# Generated by Django 2.0 on 2018-08-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20180831_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='actual_reps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
