# Generated by Django 2.0 on 2018-08-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20180831_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='set_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
