# Generated by Django 2.0 on 2018-08-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_exerciseset_set_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
